on:
  workflow_dispatch:

name: Staging Deployment
jobs:
  build_and_push_to_registry:
    name: Build Docker Image and Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: repareo/garage-dashboard:stage${{ github.run_number }}
          build-args: |
            TOKEN=${{ secrets.CI_ACCESS_TOKEN }}

  deploy-to-argocd:
    name: Deploy new image tag to argocd repo
    runs-on: ubuntu-latest
    needs: build_and_push_to_registry
    steps:
      - name: Check into argo-repo-sync
        uses: actions/checkout@v3
        with:
          repository: "repareo/gke-single-cluster-infra-argocd"
          token: ${{ secrets.CI_ACCESS_TOKEN }}
      - name: Update image tag in argo Rollout
        run: |
          sed -i -e 's/\bstage\w*/stage${{ github.run_number }}/g' deployments/staging-live/garage-dashboard/rollout.yaml
      - name: Commit changes and open PR in argocd repo
        run: |
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
          git add deployments/staging-live/garage-dashboard/rollout.yaml
          git commit -m "CI Pipeline: Deploy new garage-dashboard image tag to Staging"
          git push origin main